---
# tasks file for Bind setup
- name: Install bind
  yum:
    pkg: bind
    state: installed

- name: Copy named conf file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0660
  notify: restart named

- name: Make named directory
  file:
    path: /etc/named
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy named conf local file
  template:
    src: named.conf.local.j2
    dest: /etc/named/named.conf.local
    owner: root
    group: named
    mode: 0640
  notify: restart named


- name: Make zones Directory
  file:
    path: /etc/named/zones
    state: directory
    owner: root
    group: named
    mode: 0750

- name: Copy forward file
  template:
    src: db.forward.j2
    dest: /etc/named/zones/db.{{ domain }}
    owner: root
    group: named
    mode: 0640
  notify: restart named

- name: Copy reverse file
  template:
    src: db.reverse.j2
    dest: /etc/named/zones/db.{{ rev_domain }}
    owner: root
    group: named
    mode: 0640
  notify: restart named


- name: Install bind utils
  yum:
    pkg: bind-utils
    state: installed

- name: Copy inventory conf file
  template:
    src: inventory.j2
    dest: /opt/inventory.conf
    mode: 0644

- selinux:
    policy: targeted
    state: permissive


- name: Install ntp
  action: yum name=ntp state=present

- name: Set timezone
  shell: timedatectl set-timezone America/Sao_Paulo

- template: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: 'resolv.conf.j2', dest: '/etc/resolv.conf' }
    - { src: 'ntpd.conf.j2', dest: '/etc/ntp.conf' }
    - { src: 'ssh.j2', dest: '/etc/ssh/sshd_config' }

  notify:
    - restart-ntpd
    - restart-sshd
